### ISSUE TITLE
Attachment are uploading, but unable to download, Code=403, Forbidden

### ISSUE THREAD

**Issue by moonchitta** [aqnouch/Signal-Setup-Guide#2]
I have successfully setup the server. Chat is working, Audio/Video call is working. Now the issue is, any media sent is able to upload to minio bucket. But on the next device, its not downloading. I checked the logs it says Code=403, Forbidden.

`2020-08-09 15:58:07.588 20781-20865/org.thoughtcrime.securesms I/BaseJob: [JOB::3c8c55c4-a1d3-4f31-a19b-26134a709602][AttachmentDownloadJob] Encountered a retryable exception. (Time Since Submission: 16376 ms, Lifespan: 86400000 ms, Run Attempt: 4/Unlimited)
    org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://ivor-pc/mychatbucket/1521406324738308139}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.downloadFromCdn(PushServiceSocket.java:777)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveAttachment(PushServiceSocket.java:493)
        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveAttachment(SignalServiceMessageReceiver.java:150)
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrieveAttachment(AttachmentDownloadJob.java:165)
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.doWork(AttachmentDownloadJob.java:137)
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:107)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
     Caused by: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://ivor-pc/mychatbucket/1521406324738308139}
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.downloadFromCdn(PushServiceSocket.java:848)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.downloadFromCdn(PushServiceSocket.java:775)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveAttachment(PushServiceSocket.java:493) 
        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveAttachment(SignalServiceMessageReceiver.java:150) 
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrieveAttachment(AttachmentDownloadJob.java:165) 
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.doWork(AttachmentDownloadJob.java:137) 
        at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:107) 
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82) 
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46) `

I am not able to rectify this, your help is needed.

**Comment by moonchitta** [comment]
solved it. Actually the docker-compose.yml, this file have bucket related commands to make it download or public. Those commands were not executing. I ran docket-compose up and then I manually executed those commands in another terminal. Now attachments are uploading as well as downloading.

**Comment by pyDjangoDev** [comment]
Hello @moonchitta 
I have set up the server successfully but the Audio/Video call is not working properly.
Could you help me, please?

**Comment by moonchitta** [comment]
1. did you setup coturn?, what ports did you allow?
2. how did you configure signal server to use coturn, share turn section in your yaml file.
3. what exactly is happening, error?

**Comment by pyDjangoDev** [comment]
Thank you for your reply.
Yes. I installed the coTurn.
I am using AWS EC2 and the security group to allow the ports.
![scg](https://user-images.githubusercontent.com/61251512/114524916-37bbdf80-9c78-11eb-8e20-a4500f522a5c.png)

**Comment by pyDjangoDev** [comment]
I don't use the linux ufw utility.

**Comment by pyDjangoDev** [comment]
what do I need to modify?
Thank you

**Comment by moonchitta** [comment]
show me you yml file of signal server, and what version of signal server are you using?

**Comment by pyDjangoDev** [comment]
I am using signal server v3.21.
![2021-04-13_16-58](https://user-images.githubusercontent.com/61251512/114526336-7900bf00-9c79-11eb-9d13-831024cfb175.png)

**Comment by moonchitta** [comment]
change 127.0.0.1 in your turn section to actual ip or domain of the server, then restart your signal server. it will be good, if you show me turnserver.conf file too.

**Comment by pyDjangoDev** [comment]
![2021-04-13_16-59](https://user-images.githubusercontent.com/61251512/114526656-c67d2c00-9c79-11eb-971e-d0034542061f.png)
![2021-04-13_17-00](https://user-images.githubusercontent.com/61251512/114526662-c7ae5900-9c79-11eb-864d-81b28cf9ed36.png)

**Comment by moonchitta** [comment]
the line realm=e2c...., just copy this realm and replace it with your 127.0.0.1 ip, do it for all 4 lines, then restart signal server. Your calls will be working.

**Comment by pyDjangoDev** [comment]
After changing the 127.0.0.1 to my ec2 domain, I have to rebuild the server code?
or just restart?

**Comment by moonchitta** [comment]
no just restart, no need of rebuilding the server.

**Comment by pyDjangoDev** [comment]
Okay. let me try.

**Comment by pyDjangoDev** [comment]
Hello @moonchitta
![image_2021_04_13T18_24_11_387Z](https://user-images.githubusercontent.com/61251512/114602751-8c3b7b00-9cc9-11eb-9a2e-c4b498d04a04.png)
When start to call, the calling screen has appeared, but it said "Network failed" and disappeared.
But the app is still ringing and the notification is still alive.
![image_2021_04_13T18_28_51_187Z](https://user-images.githubusercontent.com/61251512/114602870-ad9c6700-9cc9-11eb-81fc-a4a1e9bdfa34.png)
When I click the notification, it shows a black screen.
![image_2021_04_13T18_29_17_190Z](https://user-images.githubusercontent.com/61251512/114602965-c3119100-9cc9-11eb-8e3b-e160578cc471.png)
On this black screen, when I press back, it is floated, and I can't close it.
![image_2021_04_13T18_29_58_655Z](https://user-images.githubusercontent.com/61251512/114603070-dcb2d880-9cc9-11eb-92af-99ad05644fb0.png)
Here is the log screen.
![image_2021_04_13T18_30_11_636Z](https://user-images.githubusercontent.com/61251512/114603119-ee947b80-9cc9-11eb-9c21-ed27676a96b5.png)

And Here are the signal server conf, coTurn conf, and logs.
![2021-04-14_02-36](https://user-images.githubusercontent.com/61251512/114603444-4f23b880-9cca-11eb-8b42-c2cb1065beac.png)
![2021-04-14_02-39](https://user-images.githubusercontent.com/61251512/114603681-9ca02580-9cca-11eb-9d0f-83608fb7e035.png)
![2021-04-14_02-29](https://user-images.githubusercontent.com/61251512/114603710-a3c73380-9cca-11eb-8cbc-1723eb571151.png)

What am I missing?

**Comment by moonchitta** [comment]
remove 'http' from your stun config in server's yml line, it should be like stun:ec2-3... and turn:ec2-3...
restart server and check again, it should work
and moreover, did you change applicationId of the Android application?

**Comment by pyDjangoDev** [comment]
Yes. Thank you for the quick reply.
I will try it right now.

**Comment by pyDjangoDev** [comment]
I didn't change the applicationId. only applicationName.

**Comment by moonchitta** [comment]
okie, make changes I have suggested, and restart server

**Comment by pyDjangoDev** [comment]
Thank you very much.
It's working well.
You are the best.

**Comment by pyDjangoDev** [comment]
I will follow you.

**Comment by moonchitta** [comment]
You are welcome
