### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by jeffgates** [aqnouch/Signal-Setup-Guide#33]
What did I miss??

java -jar service/target/TextSecureServer-3.21.jar server service/config/config.yml

INFO  [2021-03-19 21:36:10,623] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-03-19 21:36:10,628] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-03-19 21:36:11,495] com.turo.pushy.apns.ApnsClientBuilder: Native SSL provider is available; will use native provider.
java.lang.ClassCastException: class java.security.KeyPair cannot be cast to class java.security.PrivateKey (java.security.KeyPair and java.security.PrivateKey are in module java.base of loader 'bootstrap')
        at org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.initializeRsaSigningKey(CanonicalRequestSigner.java:64)
        at org.whispersystems.textsecuregcm.gcp.CanonicalRequestSigner.<init>(CanonicalRequestSigner.java:23)
        at org.whispersystems.textsecuregcm.controllers.AttachmentControllerV3.<init>(AttachmentControllerV3.java:46)
        at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:304)
        at org.whispersystems.textsecuregcm.WhisperServerService.run(WhisperServerService.java:151)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at org.whispersystems.textsecuregcm.WhisperServerService.main(WhisperServerService.java:406)

**Comment by jeffgates** [comment]
I went through and re-did each pem and found the issue.
